# ✈️ Flight Prices Cleaning Notebook

This notebook reads a CSV containing flight price data, cleans the 'price' column, filters out low prices, and sorts the data.

In [18]:
import re
import pandas as pd
import numpy as np

def duration_to_hours(duration_str):
    if isinstance(duration_str, str):
        hours = 0
        minutes = 0
        hr_match = re.search(r'(\d+)\s*hr', duration_str)
        min_match = re.search(r'(\d+)\s*min', duration_str)
        if hr_match:
            hours = int(hr_match.group(1))
        if min_match:
            minutes = int(min_match.group(1))
        
        # Guard: if minutes >= 60, normalize
        hours += minutes // 60
        minutes = minutes % 60

        total_hours = hours + minutes / 60
        return round(total_hours, 2)
    else:
        return None

## 📖 Read and clean the CSV file

In [20]:
# Replace with your actual file path if needed
file_path = 'results\\1784900316.277417\\results.csv'
df = pd.read_csv(file_path)

# Remove commas, convert to numeric, turn errors into NaN
df['price'] = pd.to_numeric(df['price'].astype(str).str.replace(',', ''), errors='coerce')
# Drop rows with NaN values in 'price' column
df = df.dropna(subset=['price'])

# Apply the duration_to_hours function to create a new column
df['duration_hours'] = df['duration'].apply(duration_to_hours)
# Drop rows with NaN values in 'duration_hours' column
df = df.dropna(subset=['duration_hours'])

# Add a new column 'days'
df['outbound'] = pd.to_datetime(df['outbound'])
df['inbound'] = pd.to_datetime(df['inbound'])
df['days'] = (df['inbound'] - df['outbound']).dt.days

# Remove rows containing 'RHO' in 'from' or 'to' columns
df = df[~df['to'].str.contains('RHO', na=False)]

df.head()

,timestamp,url,status,from,to,outbound,inbound,error,attempts,duration,price,airline,time,duration.1,type,duration_hours,days
0,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,TRN,BOG,2027-02-13,2027-02-28,NaN,1,14 hr 55 min,766.0,IberiaLATAMOperated by Air Nostrum for Iberia,12:00PM 8:55PM,14 hr 55 min,1 stop,14.92,15
1,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,MXP,BOG,2027-02-12,2027-02-27,NaN,1,16 hr 40 min,768.0,IberiaLATAM,10:15AM 8:55PM,16 hr 40 min,1 stop,16.67,15
2,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,MXP,BOG,2027-02-13,2027-02-28,NaN,1,31 hr 20 min,724.0,Delta,1:05PM 2:25PM+1,31 hr 20 min,1 stop,31.33,15
3,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,MXP,KTI,2027-02-12,2027-02-27,NaN,1,14 hr 50 min,810.0,Etihad,9:35PM 6:25PM+1,14 hr 50 min,1 stop,14.83,15
6,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,TRN,SAI,2027-02-13,2027-02-28,NaN,1,18 hr 40 min,1080.0,"British Airways, Bangkok AirwaysOperated by BA...",6:05PM 6:45PM+1,18 hr 40 min,2 stops,18.67,15

## 🔍 Remove durations up to X hours

In [21]:
df = df[df['duration_hours'] < 15]

## 🔍 Remove prices up to X euro

In [22]:
df = df[df['price'] < 1000]

## 📊 Sort by price ascending

In [23]:
df = df.sort_values(by='price', ascending=True)

# Final result
df.reset_index(drop=True, inplace=True)
df

,timestamp,url,status,from,to,outbound,inbound,error,attempts,duration,price,airline,time,duration.1,type,duration_hours,days
0,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,TRN,BOG,2027-02-13,2027-02-28,NaN,1,14 hr 55 min,766.0,IberiaLATAMOperated by Air Nostrum for Iberia,12:00PM 8:55PM,14 hr 55 min,1 stop,14.92,15
1,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,FCO,KTI,2027-02-12,2027-02-27,NaN,1,14 hr 25 min,777.0,Etihad,10:00PM 6:25PM+1,14 hr 25 min,1 stop,14.42,15
2,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,FCO,BOG,2027-02-12,2027-02-27,NaN,1,14 hr 55 min,778.0,IberiaLATAM,12:00PM 8:55PM,14 hr 55 min,1 stop,14.92,15
3,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,MXP,KTI,2027-02-12,2027-02-27,NaN,1,14 hr 50 min,810.0,Etihad,9:35PM 6:25PM+1,14 hr 50 min,1 stop,14.83,15

## 📊  Find the cheapest flight per route

In [24]:
best_per_route = df.loc[df.groupby(['from', 'to'])['price'].idxmin()]
best_per_route

,timestamp,url,status,from,to,outbound,inbound,error,attempts,duration,price,airline,time,duration.1,type,duration_hours,days
2,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,FCO,BOG,2027-02-12,2027-02-27,NaN,1,14 hr 55 min,778.0,IberiaLATAM,12:00PM 8:55PM,14 hr 55 min,1 stop,14.92,15
1,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,FCO,KTI,2027-02-12,2027-02-27,NaN,1,14 hr 25 min,777.0,Etihad,10:00PM 6:25PM+1,14 hr 25 min,1 stop,14.42,15
3,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,MXP,KTI,2027-02-12,2027-02-27,NaN,1,14 hr 50 min,810.0,Etihad,9:35PM 6:25PM+1,14 hr 50 min,1 stop,14.83,15
0,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,TRN,BOG,2027-02-13,2027-02-28,NaN,1,14 hr 55 min,766.0,IberiaLATAMOperated by Air Nostrum for Iberia,12:00PM 8:55PM,14 hr 55 min,1 stop,14.92,15

## 📊   Find the shortest flight per route

In [25]:
df['price_per_hour'] = (df['price'] / df['duration_hours']).round(2)
best_tradeoffs = df.sort_values(by='price_per_hour')
best_tradeoffs

,timestamp,url,status,from,to,outbound,inbound,error,attempts,duration,price,airline,time,duration.1,type,duration_hours,days,price_per_hour
0,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,TRN,BOG,2027-02-13,2027-02-28,NaN,1,14 hr 55 min,766.0,IberiaLATAMOperated by Air Nostrum for Iberia,12:00PM 8:55PM,14 hr 55 min,1 stop,14.92,15,51.34
2,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,FCO,BOG,2027-02-12,2027-02-27,NaN,1,14 hr 55 min,778.0,IberiaLATAM,12:00PM 8:55PM,14 hr 55 min,1 stop,14.92,15,52.14
1,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,FCO,KTI,2027-02-12,2027-02-27,NaN,1,14 hr 25 min,777.0,Etihad,10:00PM 6:25PM+1,14 hr 25 min,1 stop,14.42,15,53.88
3,1.784900e+09,https://www.google.com/travel/flights?q=Flight...,success,MXP,KTI,2027-02-12,2027-02-27,NaN,1,14 hr 50 min,810.0,Etihad,9:35PM 6:25PM+1,14 hr 50 min,1 stop,14.83,15,54.62

## 💾 Save results to CSV file

In [26]:
df = df.drop(columns=['duration_hours'])
df.to_csv(f'{file_path}_cleaned.csv', index=False)